body:
  - type: dropdown
    id: disruption-type
    attributes:
      label: What is the disruption type?
      options:
        - Service degradation
        - Scheduled maintenance
    validations:
      required: true
  - type: input
    id: start-time
    attributes:
      label: Start time
      description: When did this issue arise at?
      placeholder: 1/12/2026 at 12:00 AM Eastern Time
    validations:
      required: true
  - type: input
    id: end-time
    attributes:
      label: Ending time
      description: When will this issue end at?
      placeholder: 1/12/2026 at 12:00 AM Eastern Time
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Affected services
      options:
        - label: TTGit
          required: true
        - label: myTT
          required: true
        - label: Website
          required: true
        - label: Documentation
          required: true
  - type: textarea
    id: disruption-information
    attributes:
      label: Information about this issue
      description: Describe the service disruption
    validations:
      required: true
